#this file must be in root of the application
#for example
# ./bin/mapedit_server
# ./mapedit.conf


[server]

# listen on address and port - use port 0 to listen on random url
listen=localhost:0
# automaticaly open default browser on start
open_browser=true

[paths]
# specifies path to SKELDAL.DDL contains original assets
# note it is case sensitive on linux platform
game_assets=./SKELDAL.DDL