#this file must be in root of the application
#for example
# ./bin/mapedit_server
# ./mapedit.conf


[server]

# listen on address and port - use port 0 to listen on random url
listen=localhost:0
# automaticaly open default browser on start
open_browser=true
# exits when user closes browser (can be delay up to 10s)
exit_on_close=true

[paths]
# path to game folder 
# default value expects that editor is located in a subdirectory on main game folder
# change this option if you need to run from other directory
game_folder=

## path where adventure files are stored
## default location is in user profile
#
adventure_folder=

