export const MAX_ACTIONS = 40;
export const MA_GEN = 0;
export const MA_SOUND = 1;
export const MA_TEXTG = 2;
export const MA_TEXTL = 3;
export const MA_SENDA = 4;
export const MA_FIREB = 5;
export const MA_DESTR = 6;
export const MA_LOADL = 7;
export const MA_DROPI = 8;
export const MA_DIALG = 9;
export const MA_SSHOP = 10;
export const MA_CLOCK = 11;
export const MA_CACTN = 12;
export const MA_LOCK = 13;
export const MA_SWAPS = 14;
export const MA_WOUND = 15;
export const MA_IFJMP = 16;
export const MA_CALLS = 17;
export const MA_HAVIT = 18;
export const MA_STORY = 19;
export const MA_IFACT = 20;
export const MA_SNDEX = 21;
export const MA_TELEP = 22;
export const MA_PLAYA = 23;
export const MA_CREAT = 24;
export const MA_ISFLG = 25;
export const MA_CHFLG = 26;
export const MA_CUNIQ = 27;
export const MA_MONEY = 28;
export const MA_GUNIQ = 29;
export const MA_PICKI = 30;
export const MA_WBOOK = 31;
export const MA_RANDJ = 32;
export const MA_THEND = 33;
export const MA_GOMOB = 34;
export const MA_SHRMA = 35;
export const MA_MUSIC = 36;
export const MA_GLOBE = 37;  // global events
export const MA_IFSEC = 38;  // if sector num
export const MA_IFSTP = 39;  // if sector type

