export interface ImageDataResult {
    width: number;
    height: number;
    data: Uint8ClampedArray;
}

/**
 * Extracts dimensions and RGBA pixel data from an HTMLImageElement.
 * @param img HTMLImageElement
 * @returns Promise resolving to ImageDataResult
 */
export function extractImageData(img: HTMLImageElement): Promise<ImageDataResult> {
    return new Promise((resolve, reject) => {
        if (!img.complete) {
            img.onload = () => resolve(getData());
            img.onerror = reject;
        } else {
            resolve(getData());
        }

        function getData(): ImageDataResult {
            const canvas = document.createElement('canvas');
            canvas.width = img.naturalWidth;
            canvas.height = img.naturalHeight;
            const ctx = canvas.getContext('2d');
            if (!ctx) throw new Error('Could not get 2D context');
            ctx.drawImage(img, 0, 0);
            const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
            return {
                width: canvas.width,
                height: canvas.height,
                data: imageData.data,
            };
        }
    });
}


/**
 * Creates an RGB color histogram from image data.
 * @param imageData ImageDataResult
 * @param q Quantization factor for RGB channels
 * @param minAlpha Minimum alpha value (inclusive)
 * @param maxAlpha Maximum alpha value (inclusive)
 * @returns list of candidated colors
 */
export function createRgbHistogram(
    imageData: ImageDataResult,
    q: number,
    minAlpha: number,
    maxAlpha: number
): { count: number; sumR: number; sumG: number; sumB: number }[] {
    const hist: Record<string, { count: number; sumR: number; sumG: number; sumB: number }> = {};
    const data = imageData.data;
    for (let i = 0; i < data.length; i += 4) {
        const r = data[i];
        const g = data[i + 1];
        const b = data[i + 2];
        const a = data[i + 3];
        if (a < minAlpha || a > maxAlpha) continue;
        const rq = Math.floor(r / q);
        const gq = Math.floor(g / q);
        const bq = Math.floor(b / q);
        const key = `${rq},${gq},${bq}`;
        if (!hist[key]) {
            hist[key] = { count: 0, sumR: 0, sumG: 0, sumB: 0 };
        }
        hist[key].count += 1;
        hist[key].sumR += r;
        hist[key].sumG += g;
        hist[key].sumB += b;
    }
    return Object.values(hist);
}

/**
 * Generates a 3D LUT (Look-Up Table) for mapping 6-bit-per-channel RGB colors to palette indices.
 * The LUT has 64x64x64 entries (256KB, 262144 bytes), each entry is a palette index (0-254).
 * Uses flood fill (BSF) to assign each color in the LUT to the nearest palette color.
 * @param palette Array of palette colors, each with r, g, b (0-255), length <= 255
 * @returns Uint8Array of size 262144 (256KB), LUT[index] = palette index
 */
export function generateRgbLut6bit(
    palette: { r: number; g: number; b: number }[]
): Uint8Array {
    const size = 64;
    const lut = new Uint8Array(size * size * size);
    lut.fill(255); // 255 = unassigned

    // Helper to get LUT index from r,g,b (6 bits each)
    function idx(r: number, g: number, b: number) {
        return (r << 12) | (g << 6) | b;
    }

    // Seed palette colors
    for (let i = 0; i < palette.length; i++) {
        const { r, g, b } = palette[i];
        const ri = r >> 2, gi = g >> 2, bi = b >> 2;
        lut[idx(ri, gi, bi)] = i;
    }

    // Flood fill using BFS
    const queue: [number, number, number][] = [];
    for (let i = 0; i < lut.length; i++) {
        if (lut[i] !== 255) {
            const r = (i >> 12) & 0x3f, g = (i >> 6) & 0x3f, b = i & 0x3f;
            queue.push([r, g, b]);
        }
    }

    const dr = [1, -1, 0, 0, 0, 0];
    const dg = [0, 0, 1, -1, 0, 0];
    const db = [0, 0, 0, 0, 1, -1];

    while (queue.length) {
        const [r, g, b] = queue.shift()!;
        const paletteIdx = lut[idx(r, g, b)];
        for (let d = 0; d < 6; d++) {
            const nr = r + dr[d], ng = g + dg[d], nb = b + db[d];
            if (
                nr >= 0 && nr < size &&
                ng >= 0 && ng < size &&
                nb >= 0 && nb < size
            ) {
                const nidx = idx(nr, ng, nb);
                if (lut[nidx] === 255) {
                    lut[nidx] = paletteIdx;
                    queue.push([nr, ng, nb]);
                }
            }
        }
    }

    return lut;
}

/**
 * Finds the nearest palette index for a given RGB color using a 6-bit LUT.
 * @param lut Uint8Array LUT generated by generateRgbLut6bit
 * @param r Red channel (0-255)
 * @param g Green channel (0-255)
 * @param b Blue channel (0-255)
 * @returns Palette index (0-254)
 */
export function findNearestColorLut(
    lut: Uint8Array,
    r: number,
    g: number,
    b: number
): number {
    const ri = r >> 2;
    const gi = g >> 2;
    const bi = b >> 2;
    const index = (ri << 12) | (gi << 6) | bi;
    return lut[index];
}

export function findQuantizationAndGeneratePalette(imageData:ImageDataResult, colors:number, minAlpha:number, maxAlpha:number
) : {r:number; g:number; b:number}[] {

    let hist;
    for (let q = 64; q>0.9 ; q/=2) {
        hist = createRgbHistogram(imageData, q, minAlpha, maxAlpha);
        if (hist.length > colors) break;        
    }
    if (!hist) return [];
    
    hist.sort((a,b)=>b.count - a.count);

    if (hist.length > colors) {

        const main = hist.slice(0, colors);
        const remaining = hist.slice(colors);

        for (const rem of remaining) {
            let minDist = Infinity;
            let nearestIdx = -1;
            const remR = rem.sumR / rem.count;
            const remG = rem.sumG / rem.count;
            const remB = rem.sumB / rem.count;
            for (let i = 0; i < main.length; i++) {
                const mainColor = main[i];
                // Use average color for distance calculation
                const mainR = mainColor.sumR / mainColor.count;
                const mainG = mainColor.sumG / mainColor.count;
                const mainB = mainColor.sumB / mainColor.count;
                const dist = (mainR - remR) ** 2 + (mainG - remG) ** 2 + (mainB - remB) ** 2;
                if (dist < minDist) {
                    minDist = dist;
                    nearestIdx = i;
                }
            }
            if (nearestIdx >= 0) {
                main[nearestIdx].count += rem.count;
                main[nearestIdx].sumR += rem.sumR;
                main[nearestIdx].sumG += rem.sumG;
                main[nearestIdx].sumB += rem.sumB;
            }
        }
        hist = main;
    }

    // Return palette as average colors
    return hist.map(c => ({
        r: Math.round(c.sumR / c.count),
        g: Math.round(c.sumG / c.count),
        b: Math.round(c.sumB / c.count),
    }));
}