//only languages suitable for ASCII code page

export const supported_languages = [
["Čeština","czech","cs","Czech"],
["Slovenčina","czech","sk","Slovak"], 
["Dansk","danish","da","Danish"],
["Nederlands","dutch","nl","Dutch"],
["English","english","en","English"],
["Suomi","finnish","fi","Finnish"],
["Français","french","fr","French"],
["Deutsch","german","de","German"],
["Magyar","hungarian","hu","Eungarian"],
["Bahasa Indonesia","indonesian","id","Indonesian"],
["Italiano","italian","it","Italian"],
["Norsk","norwegian","no","Norwegian"],
["Polski","polish","pl","Polish"],
["Português","portuguese","pt","Portuguese"],
["Português-Brasil","brazilian","pt-BR","Brazilian"],
["Română","romanian","ro","Romanian"],
["Español-España","panish","es","Panish"],
["Español-Latinoamérica","latam","es-419","Latam"],
["Svenska","swedish","sv","Swedish"],
]

export const ascii_languages = {
  "en": "English",
  "cs": "Čeština",
  "sk": "Slovencina",
  "isv":"Medžuslovjansky",
  "pl": "Jezyk polski",
  "hu": "Magyar",
  "fr": "Francais",
  "es": "Espanol",
  "pt": "Portugues",
  "it": "Italiano",
  "nl": "Nederlands",
  "da": "Dansk",
  "sv": "Svenska",
  "no": "Norsk",
  "is": "Islenska",
  "fi": "Suomi",
  "et": "Eesti keel",
  "lv": "Latviesu valoda",
  "lt": "Lietuviu kalba",
  "eo": "Esperanto",
  "la": "Latina",
  "id": "Bahasa Indonesia",
  "ms": "Bahasa Melayu",
  "tl": "Wikang Tagalog",
  "ceb": "Sinugbuanong Binisaya",
  "ilo": "Ilokano",
  "bcl": "Bikol",
  "hil": "Hiligaynon",
  "war": "Waray",
  "pam": "Kapampangan",
  "sw": "Kiswahili",
  "so": "Af Soomaali",
  "af": "Afrikaans",
  "kg": "Kikongo",
  "ln": "Lingala",
  "tn": "Setswana",
  "st": "Sesotho",
  "bem": "Chibemba",
  "sn": "chiShona",
  "zu": "isiZulu",
  "xh": "isiXhosa",
  "ha": "Hausa",
  "yo": "Yoruba",
  "ig": "Igbo",
  "haw": "Olelo Hawaii",
  "mi": "Te Reo Maori",
  "sm": "Gagana Samoa",
  "to": "Lea faka-Tonga",
  "fj": "Na Vosa Vakaviti",
  "tpi": "Tok Pisin",
  "bi": "Bislama",
  "mh": "Kajin Majol",
  "ia": "Interlingua",
  "io": "Ido",
  "vo": "Volapuk",
  "jbo": "lojban",
  "de": "Deutsch",
  "ro": "Limba romana",
  "tr": "Turkce",
  "sq": "Shqip",
  "vi": "Tieng Viet",
  "hr": "Hrvatski jezik",
  "sl": "Slovenscina",
  "bs": "Bosanski jezik",
  "sr": "Srpski",
  "mk": "Makedonski",
  "jv": "Basa Jawa",
  "su": "Basa Sunda",
  "mg": "Malagasy",
  "rot": "Rotokas",
  "qu": "Runa Simi"  
};