export const publish_tags = [
    "Base game extension",
    "Rovenland",
    "Custom world",
    "New adventure",
    "Story Driven",
    "Combat Focused",
    "Balanced",
    "Puzzle-Oriented",
    "Exploration",
    "Linear story",
    "Branching story",
    "Multiple paths",
    "Multiple endings",
    "Short",
    "Long",
    "Epic",
    "Easy",
    "Tutorial",
    "Hard",
    "Lore-Friendly",
    "Spin-Off",
    "Prequel",
    "No magic",
    "No combat",
    "Pre-release",
    "Demo",
]