export const MainStringtable = [
[0,"UI: Controler Info"],
[1,"Playlist main menu"],
[2,"Character Generator: STRENGTH: %d-%d"],
[3,"Character Generator: MAGIC: %d-%d"],
[4,"Character Generator: SPEED: %d-%d"],
[5,"Character Generator: DEXTERITY: %d-%d"],
[7,"Intro animation"],
[10,"Character sheet: Strength"],
[11,"Character sheet: Magic"],
[12,"Character sheet: Speed"],
[13,"Character sheet: Dexterity"],
[14,"Character sheet: Lives"],
[15,"Character sheet: Condition"],
[16,"Character sheet: Mana"],
[17,"Character sheet: Defense"],
[18,"Character sheet: Attack"],
[19,"Character sheet: Bonus"],
[20,"Character sheet: Action"],
[21,"Character sheet: Protections:"],
[22,"Character sheet: Fire"],
[23,"Character sheet: Water"],
[24,"Character sheet: Earth"],
[25,"Character sheet: Air"],
[26,"Character sheet: Mind"],
[30,"Character sheet: Exp."],
[31,"Character sheet: Level"],
[35,"Niche: Item is too large"],
[36,"Niche: To many items"],
[37,"Casting: (caster: %s victim - he %s) to far."],
[38,"Casting: (caster: %s victim - she %s) to far"],
[40,"Battle Actions: '%d'"],
[41,"Battle: Attack"],
[42,"Battle: Move"],
[43,"Battle: Cancel"],
[44,"Battle: Escape"],
[45,"Battle: Rearm"],
[46,"Battle: State"],
[47,"Battle: Magic"],
[48,"Battle: Start"],
[49,"Battle: Throw"],
[50,"Battle: Combat in Progress"],
[51,"Options: Overall Music Sounds Treble Bass Speed"],
[53,"Options: Swap Sides"],
[54,"Options: CRT Filter"],
[55,"Options: Walking"],
[56,"Options: Jumping"],
[57,"Options: Fast"],
[58,"Options: Slow"],
[59,"Options: Turning"],
[60,"Battle movement 1: You can take %d step."],
[61,"Battle movement 2-4: You can take %d steps."],
[62,"Battle movement 5 and more: You can take %d steps."],
[63,"Battle movement finish: Press ENTER when ready."],
[65,"Game Over"],
[66,"Movement: You need to wait for others."],
[69,"Characte sheet: Food"],
[70,"Characte sheet: Water"],
[71,"Rest: Hours slept: %d"],
[72,"Battle: %s has no arrows."],
[75,"Save: <empty slot>"],
[76,"UI: Confirm exit game"],
[77,"UI: Yes Button"],
[78,"UI: No Button"],
[79,"Save: Corrupted slot"],
[80,"UI: OK Button"],
[81,"UI: You cannot save during combat"],
[82,"Battle: Choose hand for %s"],
[83,"Battle: Left hand"],
[84,"Battle: Right hand"],
[85,"Teleport: Teleportation spell failed"],
[86,"Spell: %s's hands are full, therefore the spell failed!"],
[87,"Teleport: %s stands at protected place"],
[88,"Teleport: The target location is protected"],
[89,"Teleport: Someone stands at protected place"],
[90,"Character sheet:Weapon bonuses"],
[91,"Character sheet:Sword"],
[92,"Character sheet:Axe"],
[93,"Character sheet:Hammer"],
[94,"Character sheet:Staff"],
[95,"Character sheet:Dagger"],
[96,"Character sheet:Ranged"],
[97,"Character sheet:Special"],
[98,"Save: Save game as"],
[100,"Shop: Attempt to sell non-empty container"],
[101,"Shop: Shopkeeper asks %d gold"],
[102,"Shop: Shopkeeper bids %d gold"],
[103,"Shop: Shopkeeper not interested."],
[104,"Shop: We don't have that much money."],
[111,"Character generator: Character need name"],
[113,"Character generator: Confirm exit"],
[114,"Character generator: Button Yes"],
[115,"Character generator: Button No"],
[116,"Character generator: Confirm restart"],
[117,"Character generator: Confirm delete"],
[118,"Message box hotkeys for Yes-No: 'YN'"],
[120,"Maps: NoSleepRegion"],
[121,"Maps: You have no idea how to leave this place."],
[130,"Maps: You found a new rune!"],
[131,"Maps: 1 gold coin on groud"],
[132,"Maps: %d (2-4) gold coins on ground"],
[133,"Maps: %d (5 more) gold couns on ground"],
[134,"Maps: Item crumbled to dust"],
[135,"Book: Page %d"],
[136,"Book: Page %d"],
[140,"Options: Show Names"],
[141,"Options: Rearrange Portraits"],
[142,"Options: Auto Attack"],
[143,"Options: Auto Save"],
[144,"Options: Speedup battles"],
[145,"Map: Adventure Length:"],
[146,"Map: 1 day, %d day and"],
[147,"Map: 2-4 days, %d days and"],
[148,"Map: 5 more days, %d days and"],
[149,"Map: 1 month, %d month and"],
[150,"Map: 2-4 months %d months and"],
[151,"Map: 5 more months, %d months and"],
[152,"Map: Time: %02d:%02d"],
[153,"Map: name format: '%s'"],
[154,"Lockpicking: (he) %s successed."],
[155,"Lockpicking: (she) %s successed."],
[156,"Lockpicking: (he) %s failed."],
[157,"Lockpicking: (she) %s failed."],
[158,"Lockpicking: (he) %s destroyed all lock picks."],
[159,"Lockpicking: (she) %s destroyed all lock picks."],
[160,"Character name: man 1"],
[161,"Character name: man 2"],
[162,"Character name: man 3"],
[163,"Character name: man 4"],
[164,"Character name: woman 1"],
[165,"Character name: woman 2"],
[166,"Character name: woman 3"],
[167,"Character name: woman 4"],
[170,"Character Generator: Accept"],
[171,"Character Generator: Start Game"],
[172,"Character Generator: Delete"],
[173,"Character Generator: All Again"],
[174,"Flute: Back button"],
[180,"Flute note: C"],
[181,"Flute note: C#"],
[182,"Flute note: D"],
[183,"Flute note: D#"],
[184,"Flute note: E"],
[185,"Flute note: F"],
[186,"Flute note: F#"],
[187,"Flute note: G"],
[188,"Flute note: G#"],
[189,"Flute note: A"],
[190,"Flute note: A#"],
[191,"Flute note: B"],
[200,"Item prerequisite: Strength: %2d"],
[201,"Item prerequisite: Magic: %2d"],
[202,"Item prerequisite: Speed: %2d"],
[203,"Item prerequisite: Dexterity: %2d"],
[205,"Playlist end game"],
[210,"Map: Large Map"],
[211,"Map: Local Map"],
[212,"Map: Show Map"],
[213,"Map: Back"],
[220,"Movement: Exhausted member."],
[230,"Shop: Haggle"],
[231,"Shop: Rejected offer."],
[232,"Shop: RejectionSeverity 1"],
[233,"Shop: RejectionSeverity 2"],
[234,"Shop: RejectionSeverity 3"],
[235,"Shop: RejectionSeverity 4"],
[236,"Shop: Rejection last item"],
[237,"Shop: No offer given"],
[238,"Shop: Your offer:"],
[239,"Shop: Back"],
[240,"Shop: User did not enter offer"],
[241,"Shop: Original price:"],
[251,"Shop: Rejected offer alt"],
[252,"Shop: RejectionSeverity 1 alt"],
[253,"Shop: RejectionSeverity 2 alt"],
[254,"Shop: RejectionSeverity 3 alt"],
[255,"Shop: RejectionSeverity 4 alt"],
[256,"Shop: Rejection last item alt"],
[73,"Spell: Death by forbidden magic %s (he)"],
[74,"Spell: Death by forbidden magic %s (she)"],
[175,"Reserved"],
[176,"Reserved"],
[32,"Launcher: Continue last save"],
[33,"Reserved"],
[52,"Reserved"],
[67,"Reserved"],
[68,"Reserved"],
[8,"Reserved"],
[9,"Reserved"],
].reduce<string[]>((a, b) => {
  a[b[0] as number] = b[1] as string;
  return a;
}, []);